site_name: AUV-DOC

nav:
  - Home: index.md
  - About: about.md
  - Development:
    - Code of conduct: Development/code_of_conduct.md
    - Contributing guidelines: Development/CONTRIBUTING.md
    - Creating a repository guide: Development/Creating_a_Repository_guide.md
  - Computer:
    - Index: computer/README.md
    - Acoustics: computer/Acoustics.md
    - Computer vision: computer/computer_vision.md
    - Simulation Engineer: computer/simulation_Engineer.md
    - ROS Engineer: computer/ROS_Engineer.md
    - Student Reports: computer/student_Reports/students.md
  - Electronics: 
    - Index: electronics/README.md
    - BMS Engineer: electronics/bms_Engineer.md
    - PCB Designer: electronics/pcb_Designer.md
    - Student Reports: 
        - Index: electronics/student_Reports/students.md
        - Nidhi and Yusra (19-20): electronics/student_Reports/nidhi_yusra_2019_20.md
        - Areeb and Farogh (19-20): electronics/student_Reports/areeb_farogh_2019_20.md

  - Marketing:
    - Index: marketing/README.md
    - Alumni Relations: marketing/alumni_relations.md
    - Creative Coordinator: marketing/creative_Coordinator.md
    - Social media manager: marketing/Social_Media_Manager.md
    - Treasurer: marketing/treasurer.md
    - Sponsorship Coordinator: marketing/sponsorship.md
    - Event Manager: marketing/event_Manager.md
    - Media Manager: marketing/media_Manager.md
    - Offline CF: marketing/offline_CF.md
    - Online CF: marketing/online_CF.md
    - Workshop Coordinator: marketing/workshop_Coordinator.md
    - Student Reports: 
        - Index: marketing/student_Reports/students.md
        - Aditi (19-20): marketing/student_Reports/aditi_2019_20.md
        - Sabeela (19-20): marketing/student_Reports/sabeela_2019_20.md
 
  - Mechanical:
    - Index: mechanical/README.md
    - Fabrication Engineer: mechanical/fabrication_Engineer.md
    - Simulation Engineer: mechanical/simulation_Engineer.md
    - Torpedo Engineer: mechanical/torpedo_Engineer.md
    - Prop Engineer: mechanical/prop_Engineer.md
    - Student Reports: mechanical/student_Reports/students.md

    
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - django
  palette:
    primary: blue
    accent: blue
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: assets/favicon.ico
  logo: assets/favicon.ico

site_url: https://auv-doc.readthedocs.io/
site_description: Project documentation with Markdown.
site_author: pnijhara

repo_url: https://github.com/auvzhcet/Documentation
edit_uri: ""

markdown_extensions:
  - toc:
      permalink: "#"

copyright: Copyright &copy; 2020 <a href="https://twitter.com/auvzhcet">AUV-ZHCET</a>, Maintained by <a href="https://twitter.com/NijharaPrajjwal">@pnijhara</a>.

plugins:
  - search
