site_name: AUV-DOC

nav:
  - Home: index.md
  - About: about.md
  - Development:
    - Code of conduct: Development/code_of_conduct.md
    - Contributing guidelines: Development/CONTRIBUTING.md
    - Creating a repository guide: Development/Creating_a_Repository_guide.md
  - Computer:
    - Index: computer/README.md
    - Acoustics: computer/Acoustics.md
    - Computer vision: computer/computer_vision.md
    - Simulation Engineer: computer/simulation_Engineer.md
    - ROS Engineer: computer/ROS_Engineer.md
    - Student Reports: computer/student_Reports/students.md
  - Electronics: 
    - Index: electronics/README.md
    - BMS Engineer: electronics/bms_Engineer.md
    - PCB Designer: electronics/pcb_Designer.md
    - Student Reports: electronics/student_Reports/students.md
  - Marketing:
    - Index: marketing/README.md
    - Alumni Relations: marketing/alumni_relations.md
    - Creative Coordinator: marketing/creative_Coordinator.md
    - Social media manager: marketing/Social_Media_Manager.md
    - Treasurer: marketing/treasurer.md
    - Sponsorship Coordinator: marketing/sponsorship.md
    - Event Manager: marketing/event_Manager.md
    - Media Manager: marketing/media_Manager.md
    - Offline CF: marketing/offline_CF.md
    - Online CF: marketing/online_CF.md
    - Workshop Coordinator: marketing/workshop_Coordinator.md
    - Student Reports: marketing/student_Reports/students.md
  - Mechanical:
    - Index: mechanical/README.md
    - Fabrication Engineer: mechanical/fabrication_Engineer.md
    - Simulation Engineer: mechanical/simulation_Engineer.md
    - Torpedo Engineer: mechanical/torpedo_Engineer.md
    - Prop Engineer: mechanical/prop_Engineer.md
    - Student Reports: mechanical/student_Reports/students.md

    
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - django
  features:
    - instant
    - tabs
  palette:
    primary: black
    accent: red
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: assets/favicon.ico
  logo: assets/favicon.ico

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/auvzhcet
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/auv_zhcet
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/in/auv-zhcet-club
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/auvzhcetclub/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/auv_zhcet/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCKnOMeEqaWUOpE7iYwUnzDg

site_url: https://auv-doc.readthedocs.io/
site_description: Project documentation with Markdown.
site_author: pnijhara

repo_url: https://github.com/auvzhcet/Documentation
edit_uri: ""

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: "#"

copyright: Copyright &copy; 2020 <a href="http://auvzhcet.in/">AUV-ZHCET</a>, Maintained by <a href="https://twitter.com/NijharaPrajjwal">@pnijhara</a>.

plugins:
  - search
